HF_EMBED: mixedbread-ai/mxbai-embed-large-v1
COHERE_RERANKER: rerank-english-v2.0
LLM_MODEL_TYPE: OPENAI
PROMPT_DIR: prompts

OPENAI:
  MODEL_NAME: gpt-4o
  MAX_TOKENS: 4096
  TEMPERATURE: 0.7
  TOP_P: 0.7
  REQUEST_TIMEOUT: 180.0
  
OLLAMA:
  MODEL_NAME: llama3.1:8b
  CTX_LENGTH: 32768
  PREDICT_LENGTH: 4096
  TEMPERATURE: 0.7
  TOP_P: 0.7
  REQUEST_TIMEOUT: 600.0

ANTHROPIC:
  MODEL_NAME: claude-3-sonnet-20240229
  MAX_TOKENS: 4096
  TEMPERATURE: 0.7
  REQUEST_TIMEOUT: 180.0

PDF_BASE_URL: https://rag-llm.s3.us-east-2.amazonaws.com/
S3_LOGS_BUCKET: altgan-logs
S3_CHAT_HISTORY: chat_logs
S3_PERSIST_BUCKET: altgan-persist
S3_PERSIST_DIR: /home/ubuntu

AWS_REGION: ap-south-1
SECRETS_MANAGER: rag_secrets
CLOUDWATCH_LOG_GROUP: altgan-log-group
CLOUDWATCH_LOG_STREAM: altgan-log-stream

QDRANT_ENABLE_HYBRID: True
FASTEMBED_SPARSE_MODEL: Qdrant/bm42-all-minilm-l6-v2-attentions
RAG_SIMILARITY_CUTOFF: 0.70
RAG_SIMILARITY_TOP_K: 20
RAG_RERANKED_TOP_N: 6
RAG_CITATION_CHUNK_SIZE: 1024
RAG_CITATION_CHUNK_OVERLAP: 32
RAG_STREAMING: True